version: '3.8'

services:
  smartdns:
    build: .
    image: smartdns:latest
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/udp"
      - "443:443"
      - "80:80"
    environment:
      - IP=${IP}
    restart: always
